---
title: "Fourth Examination Study Guide"
output:
  html_document:
    theme: readable
  pdf_document: default
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

`r ifelse(knitr::is_html_output(), "You can also download a [PDF](e4-studyguide.pdf) copy of this study guide.", "")`

1. Understand what might be reasonable *null* and *alternative* hypotheses for a given problem (note that for alternative hypotheses there may be more than one "right answer" since we have a choice between one-sided and two-sided hypotheses/tests). 

0. Understand the *roles* of the null and alternative hypotheses in a statistical test.

0. Be able to correctly compute the appropriate *test statistic* (i.e., $z$ or $t$) for a statistical test.

0. Understand the *definition* of a p-value --- it is a probability, but a probability of what?

0. Understand how to *compute* a p-value based on a $z$ or $t$ test statstic. 

0. Understand the *decision rule* for whether or not to reject a null hypothesis. 

0. Understand what is meant by *statistically significant* and how it relates to the decision made be a statistical test.

0. Understand how to conduct a statistical test concerning $\mu$ using a *confidence interval*. 

0. Understand *simple* versus *composite* hypotheses. 

0. How do we conduct a statistical test with a *composite* null hypothesis?

0. Understand how to conduct a *sign test* --- mainly how do we compute the p-value for the test?

0. What are *type I* and *type II* errors?

0. What is the probability of making a type I error (assuming the null hypothesis is true)?

0. How does increasing/decreasing the significance level affect the probabilities of type I and type II errors (assuming such an error is possible)?

0. What is meant by the *power* of a statistical test? 

0. What can be done to increase the power of a statistical test?

0. As usual, be comfortable with notation (e.g., $H_0$, $H_a$, $\mu$, $p$, $\bar{x}$, $s$, $n$, $\hat{p}$, $z$, $t$, $\alpha$).

Formulas/expressions you should understand when and how to use. 

$$
  z = \frac{\hat{p}-p}{\sqrt{p(1-p)/n}}
$$
$$
  t = \frac{\bar{x}-\mu}{s/\sqrt{n}}
$$
$$
  np \ge 15, \ \ \ n(1-p) \ge 15
$$