---
title: "Final Examination Study Guide"
output:
  html_document:
    theme: readable
  pdf_document: default
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

`r ifelse(knitr::is_html_output(), "You can also download a [PDF](final-studyguide.pdf) copy of this study guide.", "")`

1. The final examination is on **Wednesday, December 15, from 8:00 to 10:00 AM**.

0. It is university policy that if you have *more than two* final examinations scheduled *on the same day based on the official final examination schedule*, then you may have the the extra final examination(s) rescheduled. If you need to have your final examination rescheduled you must make arrangements with me *before* the final examination. 

0. The format for the final examination is the similar to the other examinations, except that it will be longer (20 to 25 questions), and many more questions will be multiple choice. The final examination focuses more on concepts and definitions and less on computations. But you should be familiar with some calculations (see the study guide below). The final will have some multiple choice questions where you need to identify either the correct formula or expression to compute, for example, a certain test statistic or confidence interval.

0. You may need a calculator for the final examination. You may also prepare up to six pages of notes (8.5 by 11 inches maximum, writing on both sides is fine). 

0. As stated on the syllabus, the final examination is worth 25% of your course grade. This is slightly less than the weight of two of the previous examinations. After dropping the lowest of the first six examinations the remaining five examinations are each worth 15% of your grade. The final examination cannot be dropped. Also please note the grade rubric on the [syllabus](syllabus.html) when determining what grade you might get in the course after taking the final. 

0. While the final examination is comprehensive, it is also limited to the topics mentioned in the study guide below. I will not ask any questions about topics not mentioned below. If you want to know if a particular topic might be on the examination, just ask. 

### Final Examination Study Guide

I have organized the study guide items by examination to make it easier for you to search through your notes.

### First Examination

1. Understand the distinction between a *sample* and a *population* of observations.

0. Understand the distinction between a *statistic* and a *parameter*.

0. Understand what is meant by *descriptive* versus *inferential* statistics.

0. Understand what is meant by a *distribution*. 

0. Understand how a histogram is constructed and interpreted as was done in the [first set of homework problems](homework-01.html).

0. Be able to compute the *mean*, *variance*, and *standard deviation* for a small set of observations of a quantitative variable (as was done in the [first set of homework problems](homework-01.html)).

0. Know how to compute a *z-score*. 

0. Understand how to apply the *empirical rule* for bell-shaped distributions (e.g., see the first problem under *Normal Distributions and the Empirical Rule* in the [third set of homework problems](homework-03.html)). 

### Second Examination

1. Understand what is meant by the *probability distribution* of a discrete random variable.

0. Know how to compute the *mean* of a *discrete* random variable given its probability distribution (see the *Means and Variances of Probability Distributions (Discrete Case)* on the [fourth set of homework problems](homework-04.html)).

0. Know how to compute a probability concerning a *continuous* random variable based on a plot of the probability density function (i.e., using the area under the curve --- see the *Computing Probabilities from Continuous Probability Distributions* and *Quartiles of the Probability Distribution of a Continuous Random Variable* in the [fourth set of homework problems](homework-04.html).

0. Understand what is meant by a *population distribution* and a *sampling distribution*.

0. Know the means and standard deviations of sampling distributions of $\bar{x}$ and $\hat{p}$.

0. Understand what is stated by the *central limit theorem*.

### Third Examination

1. What is a *standard error*? 

0. What is a *margin of error*? 

0. Understand when and how you would use each of the following formulas for *confidence intervals*:
$$
  \hat{p} \pm z\sqrt{\hat{p}(1-\hat{p})/n} \ \ \ \text{and} \ \ \ \bar{x} \pm ts/\sqrt{n}.
$$

0. What is meant by the *confidence level* of a confidence interval?

0. Understand the "anatomy" of a confidence interval --- i.e., point estimate, margin of error, standard score, and standard error. 

### Fourth Examination

1. What is meant by the term *statistically significant*? 

0. Understand the roles of the *null* and *alternative* hypothesis in a statistical test.

0. Understand when and how you would use each of the following formulas for *test statistics*: 
$$
  z = \frac{\hat{p} - p}{\sqrt{p(1-p)/n}} \ \ \ \text{and} \ \ \ t = \frac{\bar{x}-\mu}{s/\sqrt{n}}.
$$

0. Know how to compute a *p-value* given the value of a test statistic like $z$ or $t$, and the degrees of freedom if using the $t$ test statistic. 

0. Know how to decide if we reject or do not reject a null hypothesis (i.e., the *decision rule* that we use to decide whether or not we reject the null hypothesis).

0. Understand how to use a *confidence interval* to conduct a statistical test. 

0. Know the two types of errors in statistical testing: *type I* and *type II*. Also know the relationship between the *significance level* ($\alpha$) and the probabilities of these types of errors.

0. Understand what is meant by the *power* of a statistical test.

### Fifth Examination

1. Understand when and how you would use each of the following formulas for *test statistics*: 
$$
  z = \frac{\hat{p}_1 - \hat{p}_2}{\sqrt{\hat{p}(1-\hat{p})\left(\frac{1}{n_1} + \frac{1}{n_2}\right)}} \ \ \ \text{and} \ \ \
  t = \frac{\bar{x}_1 - \bar{x}_2}{\sqrt{\frac{s_1^2}{n_1} + \frac{s_2^2}{n_2}}}.
$$

0. Understand when and how you would use each of the following formulas for *confidence intervals*:
$$
  \hat{p}_1 - \hat{p}_2 \pm z \sqrt{\frac{\hat{p}_1(1-\hat{p}_1)}{n_1} + \frac{\hat{p}_2(1-\hat{p}_2)}{n_2}} \ \ \ \text{and} \ \ \ \bar{x}_1 - \bar{x}_2 \pm t \sqrt{\frac{s_1^2}{n_1} + \frac{s_2^2}{n_2}}.
$$

0. Understand the distinction between *independent* and *dependent* samples, and the advantages of the latter.

0. Understand the sampling designs we covered including *simple random sampling*, *stratified random sampling*, *one-stage and two-stage cluster sampling*, and *systematic sampling*. 

### Sixth Examination

1. Understand how the $X^2$ test statistic is computed for a goodness-of-fit test, and how the expected counts are computed for a goodness-of-fit test and a test of independence. 

0. Understand the purpose of Cramer's V.

0. Understand the purpose of McNemar's test.

0. Know how to use the chi-squared ($\chi^2$) distribution for computing p-values using the $X^2$ test statistic.

0. Know the purpose of a mark-recapture study and how to use the data from such a study to estimate the population size. 

### Correlation and Regression 

See the lectures for study guide questions on correlation and regression.

