---
title: "Syllabus for Statistical Methods (Stat 251)"
subtitle: "Section 02 (Johnson), Spring 2022"
output: 
  html_document: 
    theme: readable
fontsize: 11pt
header-includes:
- \pagenumbering{gobble}
---

`r ifelse(knitr::is_html_output(), "You can [download a PDF version](syllabus.pdf) of this syllabus.", "")`

\raggedright

**Instructor**: Dr. Timothy R. Johnson, Professor of Statistics, Department of Mathematics and Statistical Science. Email: <trjohns@uidaho.edu>. Office phone: 208-885-2928. Department phone: 208-885-6742. My office is [Brink 417](https://goo.gl/maps/zcpTXzbPCGWGj7tM9) and my office hours are 10:30 to 11:20 on Monday, Wednesday, and Friday, but I am available to meet other times. You are welcome to make an appointment or drop-in without an appointment. I can meet in person or over Zoom. If you would like to meet over Zoom, email me and I will send you a link.

**Learning Outcomes**: The learning outcomes for this course are a familiarity with the concepts of statistical description, statistical inference (including estimation, confidence intervals, statistical tests, and prediction), and the relationship between design and inference. Students should become familiar with specific methods for inferences concerning means and proportions for one- and two-sample designs, and some methods for bivariate data including contingency tables, correlation, and regression. Students should also gain an understanding of some of the underlying theoretical foundations of statistical inference including probability theory, random variables, and sampling distributions.

**Prerequisites**: One of the following: Math 143 (with grade of 'C' or better), Math 160, Math 170, or sufficient score on SAT, ACT, or math placement test (see [www.uidaho.edu/registrar/registration/placement](http://www.uidaho.edu/registrar/registration/placement)).

**Textbook**: There is no textbook. Lectures and lecture notes will be your source of material. For those who would like to consult a textbook there are some free books available online such as [OpenIntro Statistics](https://www.openintro.org/stat). But all material for which you are responsible will be covered in lecture.

**Course Website**: Most course materials including lecture notes, homework assignments, study guides, this syllabus, and other materials can be found on the course website [trobinj.github.io/stat251](https://trobinj.github.io/stat251). Note that this is separate from [Canvas](http://canvas.uidaho.edu), which will only be used for examination scores. Canvas does have a link to the course website. 

**Homework**: Homework assignments be made available periodically on the [course website](https://trobinj.github.io/stat251) (see the [lectures](https://trobinj.github.io/stat251/lectures) section). Homework assignments will *not* be collected/graded. Some computational problems in the examinations are based on homework problems (although the numbers may be changed) so it is highly recommended that you have worked through the homework problems before each examination in advance.

**Examinations**: There are six examinations (not including the final examination). The dates of these examinations are 1/28, 2/14, 3/7, 3/30, 4/15, and 4/29. These dates may be postponed if unforeseen circumstances delay my progression through the material in lecture. You will have the full class period (50 minutes) for each examination. The question formats are multiple choice and short answer. A page of formulas will be provided with each examination, but the formulas will not be labeled. You are permitted to use one page of notes during the examinations (8.5 by 11 inches maximum, writing on both sides is fine). Calculators are permitted (and sometimes necessary), but must not be capable of communication. Notes and calculators used during the examination may not be shared. Study guides for examinations will be made available on the course website in the [lectures section](https://trobinj.github.io/stat251/lectures.html) typically two lecture days before the examination. Make-ups for missed examinations will only be permitted for documented university sanctioned events or in extreme circumstances. Notice of a missed examination due to a foreseeable absence must be given *at least one week before* the scheduled day of the examination. Notice of a missed examination due to unforeseeable absence must be made *before the end of the day* for which the examination was scheduled. If I contact you to schedule a make-up a examination you must respond *promptly* (i.e., the same day) or you may not be able to make up the examination. 

**Final Examination**: The final examination is on Monday, May 9th, from 10:15 AM to 12:15 PM. The final examination may not be taken at another time unless, as according to university policy, you have more than two final examinations on that day, or a conflict with a documented university sanctioned event. The amount of time permitted to complete the final examination is two hours (120 minutes). The final examination is like that of the other examinations except that it is comprehensive and longer. A study guide for the final examination will be made available. Policies regarding the first six examinations also apply to the final examination, except that you are permitted to use up to five pages of notes for the final examination (8.5 by 11 inches maximum, writing on both sides is fine).

**Grading**: The first six examinations altogether are worth 75% of your course grade. Your lowest score of these six examinations will be dropped when grades are determined. The remaining five examinations are thus each worth 15% of your course grade. The final examination is worth the remaining 25% of your course grade. The final examination may not be dropped. Letter grades for the course will be assigned according to the following rubric: A (87.5%-100%), B (75%-87.5%), C (62.5%-75%), D (50%-62.5%), F (less than 50%). Course grades are based solely on the examination scores and the grading rubric described above. Changes to the grading system (e.g., the grade rubric or the weights) will not result in any students getting a lower letter grade than that obtained using the system described above.

**SI-PASS**: **S**upplemental **I**nstruction via **P**eer **A**ssisted **S**tudy **S**essions ([SI-PASS](https://www.uidaho.edu/current-students/academic-support/asp/tcs/si)) are peer-led, group study sessions scheduled outside of class time. These sessions are led by an SI-PASS Leader, who is a student who has taken this course and is an expert in the subject area. The SI-PASS Leader facilitates the study sessions with a variety of activities aimed to help students master course content and develop effective study skills. These sessions are free, voluntary, and anonymous for students to attend. Your SI-PASS leader is Rebecca Kirkland (<rkirkland@uidaho.edu>). The SI-PASS sessions will start on 1/18. The sessions will be on Monday from 4:00 to 4:50 PM, Tuesday from 6:30 to 7:20 PM, and Thursday from 5:30 to 6:20 PM. The sessions will meet in TLC 040 (the same room as lecture). If you have questions, please talk to your SI-PASS Leader or email <si-pass@uidaho.edu>. 

**Tutoring**: The Statistics Assistance Center (SAC) is a free drop-in tutoring service located in the library. See [www.uidaho.edu/sci/stat/about/sac](http://www.uidaho.edu/sci/stat/about/sac) for more information. Tutoring is also available through Academic Support Programs. See [www.uidaho.edu/current-students/academic-support/asp/tcs/tutoring](https://www.uidaho.edu/current-students/academic-support/asp/tcs/tutoring) for more information.

**Academic Honesty**: You are responsible for being aware of the policies of the University of Idaho on academic honesty. See Section A-1 of Article II of the [Student Code of Conduct](http://www.uidaho.edu/student-affairs/dean-of-students/student-conduct/student-code-of-conduct). This includes but is not limited to cheating, facilitation of cheating, and furnishing false information or false representation. Breaches of academic honesty will not be tolerated, and will result in a F for the course and referral to the Dean of Students for further disciplinary action.

**Disability Access**: Students with disabilities needing accommodations to fully participate in this class should contact Center for Disability Access and Resources (CDAR). All accommodations must be approved through CDAR prior to being implemented. To learn more about the accommodation process, visit CDAR's website at [www.uidaho.edu/cdar](https://www.uidaho.edu/current-students/cdar) or call 208-885-6307.

**Title IX**: University of Idaho is committed to creating a safe learning environment for all students. Consistent with this, UI policy and Title IX prohibit sexual misconduct, which includes sex or gender based harassment, sexual assault, intimate partner violence, stalking, and retaliation. If you have experienced any form of sexual misconduct, know that help and support are available. Please be aware that all University of Idaho employees are mandatory reporters and are required to report any information they receive about sexual misconduct to the university’s Title IX Coordinator within 24 hours (Idaho State Board Policy, Section I, I.T.). Visit [www.uidaho.edu/ocri/title-nine/resources](http://www.uidaho.edu/ocri/title-nine/resources) to learn more about which resources on campus and within our community are confidential. If you would like to report an incident, you may do so anonymously by visiting [www.uidaho.edu/vandalcare](https://www.uidaho.edu/vandalcare) or you can directly contact the Office of Civil Rights and Investigations at 208-885-4285 or <ocri@uidaho.edu>. 

**Healthy Vandals Pledge**: Students are required to follow the [Healthy Vandals Pledge](https://www.uidaho.edu/vandal-health-clinic/coronavirus/healthy-vandal-pledge).

1. **Daily Symptom Monitoring and In-Person Class Attendance**. Evaluate your own health status before attending in-person classes and refrain from attending class in-person if you are ill, if you are experiencing any of the [known symptoms of COVID-19](https://www.cdc.gov/coronavirus/2019-ncov/symptoms-testing/symptoms.html), or if you have tested positive for COVID-19 or have been potentially exposed to someone with COVID-19. 

    - Stay home if you experience any symptoms related to COVID-19 and that are not attributed to a non-infectious health condition regardless of how mild.
    
    - Contact your medical provider or local Idaho Public Health District for assessment of symptoms and possible COVID-19 testing. Positive COVID-19 tests should be submitted via a [VandalCare Report](https://www.uidaho.edu/student-affairs/dean-of-students/vandalcare) in order to make arrangements that involve classroom absences due to illness, and/or quarantine or isolation requirements directed by a medical provider.

2.  **Face Masks**. All faculty, staff, students and visitors across all U of I locations must use face masks whenever indoors at any U of I buildings. You are required to wear a face mask over your nose and mouth indoors at all times.

    - If you have a medical condition that affects your ability to comply with the face covering policy, please contact the [Center for Disability Access and Resources (CDAR)](https://www.uidaho.edu/current-students/cdar) to request a reasonable accommodation.

    - Failure to wear a face covering means you will be required to leave the classroom. If a disruption to the learning experience occurs due to repeated offence and/or egregious behavior, it will be referred to the Dean of Students Office for potential code violation. 

    All students are highly encouraged to get vaccinated for COVID-19. Refer to the [Vandal Health Clinic](https://www.uidaho.edu/vandal-health-clinic/coronavirus/vaccine) for more information about vaccinations. Your instructor has been vaccinated for COVID-19. 

